### ISSUE TITLE
Conditional fields

### ISSUE THREAD

**Issue by jaapie1989** [nk-o/lazy-blocks#129] opened 2020-03-26 11:02 UTC
Dear Developers,

Big thanks and love your work!  Is it possible to add conditional fields?

**Example**: Show input field when certain checkbox is checked 

Keep up the good work!

**Comment by nk-o** [comment] 2020-03-29 13:35
Duplicate of https://github.com/nk-o/lazy-blocks/issues/129

This feature will be added, but currently, we are working on other projects. Feel free to add PRs https://github.com/nk-o/lazy-blocks/pulls

**Closed by nk-o** 2020-03-29 13:35 UTC
