### ISSUE TITLE
Create a taxonomy control

### ISSUE THREAD

**Issue by janwidmer** [nk-o/lazy-blocks#169] opened 2020-09-28 20:47 UTC
Hey there,

I am using Lazy Blocks and I really like it. Now I am looking to create a block, where I can choose a taxonomy element, e.g. a category to filter posts in the block later.

I guess, I would need to create a custom control to be able to select a category. As I have not done that yet, I am looking for some help which points me in a good direction.

Anyone there, who has already built something like that?

**Comment by nk-o** [comment] 2020-09-29 14:05
Duplicate of #8

**Closed by nk-o** 2020-09-29 14:05 UTC
