### ISSUE TITLE
Select in Repeater not Getting First Value

### ISSUE THREAD

**Issue by brownrl** [nk-o/lazy-blocks#122] opened 2020-02-27 14:21 UTC
When I have a select inside of a repeater all of the options show which is correct, but unless the user explicitly chooses a new value, the value doesn't come through. So create a new repeater row, do nothing to the select and then save. Then on the front end, the value/array is not there/set. I can get around this by setting the first option to "Select an option" which makes the user select one and the in the template use the php coalesce operator '??'. However, to me it seems that the first option if nothing is done should be the "default" option and the value should come through.

If you point me in the right direction a little, I can branch and try to solve myself here and request it back.

**Comment by nk-o** [comment] 2020-03-07 16:14
This issue will be fixed in future plugin updates. Duplicate of https://github.com/nk-o/lazy-blocks/issues/120

**Closed by nk-o** 2020-03-07 16:14 UTC
